@startuml
JdbcTemplate -> DataSourceProxy :获取fescar数据代理
DataSourceProxy ->ConnectionProxy:获取fescar连接代理
ConnectionProxy -> PreparedStatementProxy: 获取statmen代理
PreparedStatementProxy-> ExecuteTemplate:execute
ExecuteTemplate-> UpdateExecutor:execute
UpdateExecutor->AbstractDMLBaseExecutor:doExecute
activate AbstractDMLBaseExecutor #FFBBBB
AbstractDMLBaseExecutor->UpdateExecutor:beforeImage();
AbstractDMLBaseExecutor->Mybatis:执行目标方法
AbstractDMLBaseExecutor->UpdateExecutor:afterImage(beforeImage)
AbstractDMLBaseExecutor->ConnectionProxy:prepareUndoLog(保存事务日志于内存ConnectionContext)
deactivate AbstractDMLBaseExecutor
AbstractDMLBaseExecutor->ConnectionProxy:commit
AbstractDMLBaseExecutor->AbstractDMLBaseExecutor: 目标方法rollback
activate ConnectionProxy #FFBBBB
ConnectionProxy->RmRpcClient:上报事务状态(commit)
ConnectionProxy->PreparedStatementProxy:save unlog
ConnectionProxy->ConnectionProxy:targe commit
ConnectionProxy->RmRpcClient:上报事务状态(commit)
activate ConnectionProxy #FFBBBB

@enduml